### ISSUE TITLE
Unable to run zTetris

### ISSUE THREAD

**Issue by ddevault** [unlimitedbacon/ztetris#7]
I just did `knightos install ports/ztetris` on a fresh userspace with a bleeding edge kernel and I can't run zTetris. The calc crashes upon launching it from the castle.

**Comment by unlimitedbacon** [comment]
This is probably the bug that was fixed by 960ecd8d26c7fd7ab3382b939b1a732902f15a3e. Let me know if it isn't

**Comment by ddevault** [comment]
Yep, seems to be fixed. Thanks!
